/**
 * The nested value objects a shipment is made of, and the mapping between them
 * and the flat columns `shipments` actually stores.
 *
 * ## Why a nested shape survives the port at all
 *
 * It would be reasonable to expect these types to have died with the
 * now-deleted `models/shipment.ts`
 * — they look like Mongoose subdocuments, and `shipments` flattens every one of
 * them into columns. They do not die, for two reasons that have nothing to do
 * with Mongo:
 *
 *  - **A job freezes the endpoints and the parcel at booking**, and reads them
 *    back through these same types — see `jobShape.ts`, whose `JobRecord`
 *    declares `pickupSnapshot`, `dropoffSnapshot` and `parcelSnapshot` as the
 *    value objects below. `jobs` FLATTENS all three into columns exactly as
 *    `shipments` does; only `quote_snapshot` and `totals` are jsonb there, and
 *    a `PriceBreakdown` is what earns it, being read as a unit and never
 *    compared across rows.
 *  - **`ProviderAdapter` takes a whole shipment.** Every external carrier is
 *    integrated behind that one interface, and an adapter reads
 *    `shipment.pickup.location.coordinates`. Handing adapters a 30-column flat
 *    row would push the ordinate lookup into every integration.
 *
 * So this module owns the shape, and the repository maps to and from it. The
 * `Value` suffix distinguishes these persisted value objects from the
 * identically-named WIRE types in `@moovo/shared-types` (`ShipmentEndpoint`,
 * `ParcelDetails`, …), which differ: the DTOs carry ISO strings and omit absent
 * optionals, and `shipment-hydration.service` is the one place that converts.
 *
 * ## The one asymmetry between the two directions
 *
 * `toShipmentRecord` is total — every row produces a record. `toShipmentColumns`
 * is not: it takes a CREATE input, which has no id, status, distance, quote ref
 * or job id, because none of those is the caller's to supply.
 */

import type { SizeClass, ShipmentType, ShipmentStatus } from '@moovo/shared-types';
import type { shipments } from '../schema/transport';

/** A `shipments` row exactly as stored — flat, 30-odd columns. */
export type ShipmentRow = typeof shipments.$inferSelect;

/**
 * A position, in GeoJSON's ordering.
 *
 * `[lng, lat]`, which is the order the coordinates array has always carried and
 * the order every adapter and hydrator reads it in. The table stores the two
 * ordinates as named columns precisely so this ordering is asserted in exactly
 * one place — here — rather than being implicit in an array index somewhere.
 */
export interface ShipmentGeoPointValue {
  type: 'Point';
  /** `[longitude, latitude]`. */
  coordinates: number[];
}

/** A postal address, as stored. */
export interface ShipmentAddressValue {
  line1: string;
  line2?: string;
  city: string;
  region?: string;
  postalCode: string;
  country: string;
}

/** One end of a shipment: where, whose, and what they said about it. */
export interface ShipmentEndpointValue {
  location: ShipmentGeoPointValue;
  address: ShipmentAddressValue;
  contactName: string;
  contactPhone: string;
  notes?: string;
}

/** Parcel dimensions in centimetres. */
export interface DimensionsCmValue {
  l: number;
  w: number;
  h: number;
}

/** What is being moved. */
export interface ParcelDetailsValue {
  weightKg: number;
  dimsCm?: DimensionsCmValue;
  sizeClass: SizeClass;
  pieces: number;
  fragile?: boolean;
}

/** When the shipment should be fulfilled. */
export interface SchedulingValue {
  kind: 'now' | 'scheduled';
  scheduledFor?: Date;
}

/** A reference photo (an Oxy media file id, plus its place in the gallery). */
export interface ShipmentPhotoValue {
  fileId: string;
  alt?: string;
  position: number;
}

/**
 * A persisted shipment, in the shape its consumers read.
 *
 * `id` rather than `_id`: the id is a uuid v7 string generated by the
 * application, and nothing downstream needs an ObjectId.
 */
export interface ShipmentRecord {
  id: string;
  senderOxyUserId: string;
  type: ShipmentType;
  status: ShipmentStatus;
  pickup: ShipmentEndpointValue;
  dropoff: ShipmentEndpointValue;
  parcel: ParcelDetailsValue;
  itemDescription: string;
  photos: ShipmentPhotoValue[];
  scheduling: SchedulingValue;
  distanceM?: number;
  quoteRef?: string;
  jobId?: string;
  createdAt: Date;
  updatedAt: Date;
}

/** What creating a shipment needs — the caller supplies no id and no status. */
export interface NewShipment {
  senderOxyUserId: string;
  type: ShipmentType;
  status: ShipmentStatus;
  pickup: ShipmentEndpointValue;
  dropoff: ShipmentEndpointValue;
  parcel: ParcelDetailsValue;
  itemDescription: string;
  photos: ShipmentPhotoValue[];
  scheduling: SchedulingValue;
}

/**
 * Assemble one endpoint from its flat columns.
 *
 * The optional address parts are OMITTED when null rather than set to
 * `undefined`, because `redaction.ts` and the hydrators both test them for
 * truthiness and the DTO contract distinguishes an absent key from a present
 * one. A `null` reaching a DTO would serialize as `"line2": null`, which the
 * wire contract does not describe.
 */
function toEndpoint(
  location: { longitude: number; latitude: number },
  address: {
    line1: string;
    line2: string | null;
    city: string;
    region: string | null;
    postalCode: string;
    country: string;
  },
  contactName: string,
  contactPhone: string,
  notes: string | null,
): ShipmentEndpointValue {
  const value: ShipmentEndpointValue = {
    location: { type: 'Point', coordinates: [location.longitude, location.latitude] },
    address: {
      line1: address.line1,
      city: address.city,
      postalCode: address.postalCode,
      country: address.country,
    },
    contactName,
    contactPhone,
  };
  if (address.line2 !== null) value.address.line2 = address.line2;
  if (address.region !== null) value.address.region = address.region;
  if (notes !== null) value.notes = notes;
  return value;
}

/**
 * The stored photo array, validated on the way out.
 *
 * `photos` is `jsonb`, so the database guarantees it is valid JSON and nothing
 * more — the column cannot state that it holds objects with a `fileId` and a
 * numeric `position`. Reading it as that shape without checking is the one
 * place in this mapper where a bad row becomes a confusing failure much later
 * (a `sort` comparing `undefined`, a media chokepoint handed a number). So the
 * cast is guarded: anything that is not the declared shape is dropped, and the
 * caller gets a well-formed array or an empty one.
 */
function toPhotos(raw: unknown): ShipmentPhotoValue[] {
  if (!Array.isArray(raw)) return [];
  const photos: ShipmentPhotoValue[] = [];
  for (const entry of raw) {
    if (typeof entry !== 'object' || entry === null) continue;
    const candidate = entry as Record<string, unknown>;
    if (typeof candidate.fileId !== 'string' || typeof candidate.position !== 'number') continue;
    const photo: ShipmentPhotoValue = { fileId: candidate.fileId, position: candidate.position };
    if (typeof candidate.alt === 'string') photo.alt = candidate.alt;
    photos.push(photo);
  }
  return photos;
}

/** Assemble the nested record a consumer reads from one flat row. */
export function toShipmentRecord(row: ShipmentRow): ShipmentRecord {
  const record: ShipmentRecord = {
    id: row.id,
    senderOxyUserId: row.senderOxyUserId,
    type: row.type as ShipmentType,
    status: row.status as ShipmentStatus,
    pickup: toEndpoint(
      { longitude: row.pickupLongitude, latitude: row.pickupLatitude },
      {
        line1: row.pickupLine1,
        line2: row.pickupLine2,
        city: row.pickupCity,
        region: row.pickupRegion,
        postalCode: row.pickupPostalCode,
        country: row.pickupCountry,
      },
      row.pickupContactName,
      row.pickupContactPhone,
      row.pickupNotes,
    ),
    dropoff: toEndpoint(
      { longitude: row.dropoffLongitude, latitude: row.dropoffLatitude },
      {
        line1: row.dropoffLine1,
        line2: row.dropoffLine2,
        city: row.dropoffCity,
        region: row.dropoffRegion,
        postalCode: row.dropoffPostalCode,
        country: row.dropoffCountry,
      },
      row.dropoffContactName,
      row.dropoffContactPhone,
      row.dropoffNotes,
    ),
    parcel: toParcel(row),
    itemDescription: row.itemDescription,
    photos: toPhotos(row.photos),
    scheduling: toScheduling(row),
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
  if (row.distanceM !== null) record.distanceM = row.distanceM;
  if (row.quoteRef !== null) record.quoteRef = row.quoteRef;
  if (row.jobId !== null) record.jobId = row.jobId;
  return record;
}

/**
 * Reassemble the parcel.
 *
 * `dimsCm` is present only when ALL THREE ordinates are, which is what the
 * source's optional `dimsCm` subdocument meant — a partial `{l, w}` was not
 * representable there and must not become representable here. Three nullable
 * columns can express it, so the reassembly is where it is refused.
 */
function toParcel(row: ShipmentRow): ParcelDetailsValue {
  const parcel: ParcelDetailsValue = {
    weightKg: row.parcelWeightKg,
    sizeClass: row.parcelSizeClass as SizeClass,
    pieces: row.parcelPieces,
    fragile: row.parcelFragile,
  };
  if (row.parcelDimsL !== null && row.parcelDimsW !== null && row.parcelDimsH !== null) {
    parcel.dimsCm = { l: row.parcelDimsL, w: row.parcelDimsW, h: row.parcelDimsH };
  }
  return parcel;
}

/**
 * Reassemble the scheduling pair.
 *
 * The `shipments_scheduling_shape_check` CHECK already guarantees the two
 * columns agree, so this reads the stored `kind` and trusts the constraint
 * rather than re-deriving the kind from whether the time is null — which would
 * be a second, quietly divergent answer to a question the database settles.
 */
function toScheduling(row: ShipmentRow): SchedulingValue {
  if (row.schedulingKind === 'scheduled' && row.scheduledFor !== null) {
    return { kind: 'scheduled', scheduledFor: row.scheduledFor };
  }
  return { kind: 'now' };
}

/** The flat column values an insert needs, minus the id the repository mints. */
export type ShipmentInsertColumns = Omit<
  typeof shipments.$inferInsert,
  'id' | 'createdAt' | 'updatedAt'
>;

/**
 * Read the `[lng, lat]` pair off an endpoint, refusing a malformed one.
 *
 * The ordinate columns are NOT NULL, so a coordinates array with fewer than two
 * finite numbers would otherwise reach the server and come back as a null
 * violation naming a column the caller never mentioned. Refusing here names the
 * endpoint instead. `Number.isFinite` rather than a length check, because
 * `[NaN, NaN]` has length two and would insert a row that no geography index
 * can place — `ST_MakePoint` is STRICT for nulls but takes a NaN happily.
 */
function ordinates(endpoint: ShipmentEndpointValue, which: 'pickup' | 'dropoff'): {
  longitude: number;
  latitude: number;
} {
  const [longitude, latitude] = endpoint.location.coordinates;
  if (!Number.isFinite(longitude) || !Number.isFinite(latitude)) {
    throw new Error(
      `Shipment ${which} location needs a finite [lng, lat] pair; received ${JSON.stringify(endpoint.location.coordinates)}`,
    );
  }
  return { longitude, latitude };
}

/**
 * Flatten a create input into columns.
 *
 * The generated `pickup_location`/`dropoff_location` geography points are NOT
 * written and must never appear here: they are `GENERATED ALWAYS`, derived from
 * the ordinate pair, and Postgres rejects an explicit write to one. That is the
 * property that makes it impossible for a point and its ordinates to disagree.
 */
export function toShipmentColumns(input: NewShipment): ShipmentInsertColumns {
  const pickup = ordinates(input.pickup, 'pickup');
  const dropoff = ordinates(input.dropoff, 'dropoff');
  return {
    senderOxyUserId: input.senderOxyUserId,
    type: input.type,
    status: input.status,

    pickupLatitude: pickup.latitude,
    pickupLongitude: pickup.longitude,
    pickupLine1: input.pickup.address.line1,
    pickupLine2: input.pickup.address.line2 ?? null,
    pickupCity: input.pickup.address.city,
    pickupRegion: input.pickup.address.region ?? null,
    pickupPostalCode: input.pickup.address.postalCode,
    pickupCountry: input.pickup.address.country,
    pickupContactName: input.pickup.contactName,
    pickupContactPhone: input.pickup.contactPhone,
    pickupNotes: input.pickup.notes ?? null,

    dropoffLatitude: dropoff.latitude,
    dropoffLongitude: dropoff.longitude,
    dropoffLine1: input.dropoff.address.line1,
    dropoffLine2: input.dropoff.address.line2 ?? null,
    dropoffCity: input.dropoff.address.city,
    dropoffRegion: input.dropoff.address.region ?? null,
    dropoffPostalCode: input.dropoff.address.postalCode,
    dropoffCountry: input.dropoff.address.country,
    dropoffContactName: input.dropoff.contactName,
    dropoffContactPhone: input.dropoff.contactPhone,
    dropoffNotes: input.dropoff.notes ?? null,

    parcelWeightKg: input.parcel.weightKg,
    parcelDimsL: input.parcel.dimsCm?.l ?? null,
    parcelDimsW: input.parcel.dimsCm?.w ?? null,
    parcelDimsH: input.parcel.dimsCm?.h ?? null,
    parcelSizeClass: input.parcel.sizeClass,
    parcelPieces: input.parcel.pieces,
    parcelFragile: input.parcel.fragile ?? false,

    itemDescription: input.itemDescription,
    photos: input.photos,

    schedulingKind: input.scheduling.kind,
    scheduledFor: input.scheduling.kind === 'scheduled' ? (input.scheduling.scheduledFor ?? null) : null,
  };
}
